image:
  name: bestitdocker/build
  username: $DOCKER_HUB_USER
  password: $DOCKER_HUB_PASSWORD
  email: $DOCKER_HUB_MAIL

pipelines:
  default:
    - step:
        script:    
          - composer --version
          - phpunit --version
          - composer install --no-ansi --no-interaction --no-progress --no-scripts
          - chmod +x ./vendor/bin/phpcs
          - chmod +x ./vendor/bin/phpunit
          - ./vendor/bin/phpcs src --standard=ruleset.xml
          - ./vendor/bin/phpunit
